# Generated by Django 5.2.15 on 2026-09-05 10:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0016_alter_accountconfiguration_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Group'), (2, 'Sub Group'), (3, 'Item')])),
                ('code_segment', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{2,3}$', 'Code segment must be 2 or 3 digits.')])),
                ('complete_code', models.CharField(db_index=True, max_length=12)),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('specification', models.CharField(blank=True, choices=[('raw_item', 'Raw Item'), ('raw_packing', 'Raw Packing'), ('finish_item', 'Finish Item'), ('finish_packing', 'Finish Packing'), ('byproduct', 'By-Product'), ('service_item', 'Service Item'), ('wage_item', 'Wage Item')], max_length=20)),
                ('quick_code', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(blank=True, choices=[('kg', 'Kg'), ('piece', 'Piece'), ('mound', 'Mound')], max_length=10)),
                ('unit_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fix_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('actual_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.productnode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prod_nodes',
                'ordering': ['complete_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entry_date', models.DateField()),
                ('source', models.CharField(choices=[('opening', 'Opening Balance'), ('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('sale', 'Sale'), ('sale_return', 'Sale Return'), ('production_in', 'Production Receipt'), ('production_out', 'Grinding Issue'), ('packing_out', 'Packing Consumption'), ('adjustment', 'Stock Adjustment')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='products.productnode')),
            ],
            options={
                'db_table': 'prod_ledgers',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('purchase_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_purchase_links', to='finance.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_link', to='products.productnode')),
            ],
            options={
                'db_table': 'prod_account_links',
            },
        ),
        migrations.CreateModel(
            name='FinishBardanaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('bag_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finish_bardana_uses', to='products.productnode')),
                ('finish_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finish_bardana_link', to='products.productnode')),
            ],
            options={
                'db_table': 'prod_finish_bardana_links',
            },
        ),
        migrations.CreateModel(
            name='ProductOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('as_of_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance', to='products.productnode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prod_opening_balances',
            },
        ),
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='products.productnode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prod_rates',
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RawBardanaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bardana_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_bardana_uses', to='products.productnode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('wheat_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_bardana_link', to='products.productnode')),
            ],
            options={
                'db_table': 'prod_raw_bardana_links',
            },
        ),
        migrations.AddIndex(
            model_name='productnode',
            index=models.Index(fields=['status', 'complete_code'], name='prod_node_status_code_idx'),
        ),
        migrations.AddIndex(
            model_name='productnode',
            index=models.Index(fields=['parent', 'code_segment'], name='prod_node_parent_seg_idx'),
        ),
        migrations.AddIndex(
            model_name='productnode',
            index=models.Index(fields=['specification', 'status'], name='prod_node_spec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productnode',
            index=models.Index(fields=['quick_code'], name='prod_node_quick_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='productnode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'code_segment'), name='prod_node_unique_segment_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='productnode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('quick_code', ''), _negated=True)), fields=('quick_code',), name='prod_node_unique_quick_code'),
        ),
        migrations.AddIndex(
            model_name='productledger',
            index=models.Index(fields=['product', '-entry_date'], name='prod_ledger_prod_date_idx'),
        ),
        migrations.AddIndex(
            model_name='productledger',
            index=models.Index(fields=['source', '-entry_date'], name='prod_ledger_src_date_idx'),
        ),
        migrations.AddIndex(
            model_name='productledger',
            index=models.Index(fields=['reference'], name='prod_ledger_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='productaccountlink',
            index=models.Index(fields=['purchase_account'], name='prod_acct_link_acct_idx'),
        ),
        migrations.AddIndex(
            model_name='finishbardanalink',
            index=models.Index(fields=['bag_item'], name='prod_fin_bard_item_idx'),
        ),
        migrations.AddIndex(
            model_name='productopeningbalance',
            index=models.Index(fields=['as_of_date'], name='prod_opening_date_idx'),
        ),
        migrations.AddIndex(
            model_name='productrate',
            index=models.Index(fields=['product', '-effective_date'], name='prod_rate_prod_date_idx'),
        ),
        migrations.AddIndex(
            model_name='productrate',
            index=models.Index(fields=['product', 'is_current'], name='prod_rate_current_idx'),
        ),
        migrations.AddIndex(
            model_name='rawbardanalink',
            index=models.Index(fields=['bardana_item'], name='prod_raw_bard_item_idx'),
        ),
    ]
