# Generated by Django 5.2.15 on 2026-09-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godowns', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productledger',
            name='bardana_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_as_bardana_entries', to='products.productnode'),
        ),
        migrations.AddField(
            model_name='productledger',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_ledger_entries', to='godowns.godown'),
        ),
        migrations.AddField(
            model_name='productnode',
            name='standard_yield_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddIndex(
            model_name='productledger',
            index=models.Index(fields=['product', 'bardana_item', '-entry_date'], name='prod_ledger_bardana_idx'),
        ),
        migrations.AddIndex(
            model_name='productledger',
            index=models.Index(fields=['godown', '-entry_date'], name='prod_ledger_godown_date_idx'),
        ),
    ]
