# Generated by Django 5.2.15 on 2026-09-20 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godowns', '0001_initial'),
        ('inventory', '0055_purchase_return_rebuild'),
        ('products', '0002_productledger_bardana_item_productledger_godown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productledger',
            name='source',
            field=models.CharField(choices=[('opening', 'Opening Balance'), ('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('sale', 'Sale'), ('sale_return', 'Sale Return'), ('production_in', 'Production Receipt'), ('production_out', 'Grinding Issue'), ('packing_out', 'Packing Consumption'), ('adjustment', 'Stock Adjustment'), ('reversal', 'Reversal')], max_length=30),
        ),
        migrations.CreateModel(
            name='PartyBardanaLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entry_date', models.DateField()),
                ('source', models.CharField(choices=[('opening', 'Opening Balance'), ('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('sale', 'Sale'), ('sale_return', 'Sale Return'), ('production_in', 'Production Receipt'), ('production_out', 'Grinding Issue'), ('packing_out', 'Packing Consumption'), ('adjustment', 'Stock Adjustment'), ('reversal', 'Reversal')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('ownership', models.CharField(blank=True, max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('bardana_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_ledger_entries', to='products.productnode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_bardana_entries', to='godowns.godown')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bardana_ledger_entries', to='inventory.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prod_party_bardana_ledgers',
                'ordering': ['-entry_date', '-id'],
                'indexes': [models.Index(fields=['party', 'bardana_item', '-entry_date'], name='prod_pbl_party_item_date_idx'), models.Index(fields=['bardana_item', '-entry_date'], name='prod_pbl_item_date_idx'), models.Index(fields=['reference'], name='prod_pbl_reference_idx')],
            },
        ),
    ]
