# Generated by Django 5.2.15 on 2026-09-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('godowns', '0001_initial'),
        ('products', '0002_productledger_bardana_item_productledger_godown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrindingVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seq_num', models.PositiveIntegerField()),
                ('voucher_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('production_from', models.TimeField()),
                ('production_to', models.TimeField()),
                ('disposal_wheat', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('disposal_bag_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('issue_area', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('total_output_kg', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('yield_percent', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('shortage_kg', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('shortage_percent', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('standard_yield_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bag_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grinding_bag_uses', to='products.productnode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grinding_vouchers', to='godowns.godown')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_grinding_vouchers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('wheat_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grinding_vouchers', to='products.productnode')),
            ],
            options={
                'db_table': 'prod_grinding_vouchers',
                'ordering': ['-date', '-seq_num'],
            },
        ),
        migrations.CreateModel(
            name='GrindingOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('unit_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('pack_qty', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('pack_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grinding_pack_uses', to='products.productnode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grinding_outputs', to='products.productnode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.grindingvoucher')),
            ],
            options={
                'db_table': 'prod_grinding_outputs',
                'ordering': ['voucher', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seq_num', models.PositiveIntegerField()),
                ('voucher_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('source_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('source_unit_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('total_output_kg', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='godowns.godown')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_conversions', to=settings.AUTH_USER_MODEL)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_sources', to='products.productnode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prod_conversions',
                'ordering': ['-date', '-seq_num'],
            },
        ),
        migrations.CreateModel(
            name='ProductConversionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('unit_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('pack_qty', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productconversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('pack_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversion_pack_uses', to='products.productnode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_outputs', to='products.productnode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prod_conversion_lines',
                'ordering': ['conversion', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='grindingvoucher',
            index=models.Index(fields=['-date', '-seq_num'], name='grind_date_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='grindingvoucher',
            index=models.Index(fields=['wheat_item', '-date'], name='grind_wheat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='grindingvoucher',
            index=models.Index(fields=['godown', '-date'], name='grind_godown_date_idx'),
        ),
        migrations.AddIndex(
            model_name='grindingvoucher',
            index=models.Index(fields=['voucher_no'], name='grind_voucher_no_idx'),
        ),
        migrations.AddConstraint(
            model_name='grindingvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('voucher_no',), name='grinding_unique_voucher_no'),
        ),
        migrations.AddIndex(
            model_name='grindingoutput',
            index=models.Index(fields=['voucher', 'line_number'], name='grind_out_voucher_line_idx'),
        ),
        migrations.AddIndex(
            model_name='grindingoutput',
            index=models.Index(fields=['product', '-id'], name='grind_out_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='grindingoutput',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('voucher', 'line_number'), name='grinding_output_unique_line'),
        ),
        migrations.AddIndex(
            model_name='productconversion',
            index=models.Index(fields=['-date', '-seq_num'], name='conv_date_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='productconversion',
            index=models.Index(fields=['source_product', '-date'], name='conv_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='productconversion',
            index=models.Index(fields=['godown', '-date'], name='conv_godown_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='productconversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('voucher_no',), name='conversion_unique_voucher_no'),
        ),
        migrations.AddIndex(
            model_name='productconversionline',
            index=models.Index(fields=['conversion', 'line_number'], name='conv_line_conv_line_idx'),
        ),
        migrations.AddIndex(
            model_name='productconversionline',
            index=models.Index(fields=['product', '-id'], name='conv_line_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='productconversionline',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('conversion', 'line_number'), name='conversion_line_unique_line'),
        ),
    ]
