# Generated by Django 5.2.15 on 2026-06-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_address_user_cnic_and_more'),
        ('hr', '0002_alter_employee_bank_alter_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='hr_employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hr.employee'),
        ),
    ]
