# Generated by Django 5.2.15 on 2026-06-18 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0002_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('nature', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('account_no', models.CharField(max_length=80, unique=True)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('account_ledger', models.CharField(choices=[('G', 'General'), ('S', 'Subsidiary')], default='G', max_length=1)),
                ('balance_income', models.CharField(choices=[('B', 'Balance Sheet'), ('I', 'Income Statement')], max_length=1)),
                ('account_nature', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('post_to_account', models.ForeignKey(blank=True, db_column='post_to_account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_accounts', to='finance.accountconfiguration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_account_configuration',
                'ordering': ['account_no'],
            },
        ),
        migrations.CreateModel(
            name='AccountVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=80, unique=True)),
                ('account_no', models.CharField(max_length=80)),
                ('voucher_date', models.DateField(default=django.utils.timezone.localdate)),
                ('voucher_type', models.CharField(choices=[('PV', 'Payment Voucher'), ('RV', 'Receipt Voucher')], max_length=2)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('double_verified', 'Double Verified')], default='created', max_length=20)),
                ('posted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('adj_entry', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('credit_card_payment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('credit_card_no', models.CharField(blank=True, max_length=40)),
                ('credit_card_expiry', models.CharField(blank=True, max_length=10)),
                ('adj_voucher', models.ForeignKey(blank=True, db_column='adj_voucher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.accountvoucher')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, db_column='conf_payment_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.paymentmethod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_account_voucher',
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_fiscal_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('line_number', models.PositiveIntegerField()),
                ('voucher_no', models.CharField(max_length=80)),
                ('account_no', models.CharField(max_length=80)),
                ('voucher_date', models.DateField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('person_organization', models.CharField(blank=True, max_length=180)),
                ('person_organization_title', models.CharField(blank=True, max_length=180)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, db_column='conf_payment_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.paymentmethod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(db_column='fin_account_voucher_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.accountvoucher')),
            ],
            options={
                'db_table': 'fin_account_voucher_lines',
                'ordering': ['voucher', 'line_number'],
                'unique_together': {('voucher', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(db_column='fin_fiscal_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='finance.fiscalyear')),
            ],
            options={
                'db_table': 'fin_fiscal_periods',
                'ordering': ['fiscal_year', 'code'],
                'unique_together': {('fiscal_year', 'code')},
            },
        ),
    ]
