# Generated by Django 5.2.15 on 2026-06-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_bank'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvoucherline',
            name='bank',
            field=models.ForeignKey(blank=True, db_column='conf_bank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.bank'),
        ),
        migrations.AddField(
            model_name='accountvoucherline',
            name='credit_card_expiry',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='accountvoucherline',
            name='credit_card_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='accountvoucherline',
            name='credit_card_payment',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='accountvoucherline',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
