# Generated by Django 5.2.15 on 2026-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_accountvoucherline_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalperiod',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='inactive', max_length=20),
        ),
    ]
