# Generated by Django 5.2.15 on 2026-07-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_chartofaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvoucher',
            name='voucher_type',
            field=models.CharField(choices=[('CN', 'Contra'), ('PV', 'Payment'), ('RV', 'Receipt'), ('JV', 'Journal'), ('SV', 'Sales'), ('PU', 'Purchase')], max_length=2),
        ),
    ]
