# Generated by Django 5.2.15 on 2026-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_accountvoucher_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvoucher',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
