# Generated by Django 5.2.15 on 2026-07-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_bank'),
        ('finance', '0006_accountvoucher_transaction_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvoucher',
            name='bank',
            field=models.ForeignKey(blank=True, db_column='conf_bank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.bank'),
        ),
    ]
