# Generated by Django 5.2.15 on 2026-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_accountvoucher_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvoucher',
            name='bank',
        ),
        migrations.AddField(
            model_name='accountvoucher',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
