# Generated by Django 5.2.15 on 2026-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_accountvoucher_bank_accountvoucher_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvoucher',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountvoucher',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
