# Generated by Django 5.2.15 on 2026-07-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_accountvoucher_wallet_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvoucher',
            name='party_account_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='accountvoucher',
            name='settlement_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=10),
        ),
    ]
