# Generated by Django 5.2.15 on 2026-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_accountvoucher_party_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
