# Generated by Django 5.2.15 on 2026-07-31 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_bank'),
        ('finance', '0012_chartofaccount_opening_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvoucher',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='accountvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('source_ref',), name='uniq_voucher_source_ref'),
        ),
    ]
