# Generated by Django 5.2.15 on 2026-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_accountvoucher_source_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvoucher',
            name='account_no',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
