# Generated by Django 5.2.15 on 2026-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_accountvoucher_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvoucher',
            name='payment_receipt',
            field=models.FileField(blank=True, upload_to='finance/payment_receipts/%Y/%m/'),
        ),
    ]
