# Generated by Django 5.2.15 on 2026-09-01 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_alter_allowancededuction_created_at_and_more'),
        ('finance', '0015_accountvoucher_payment_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='accountconfiguration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountvoucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='accountvoucher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountvoucherline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='accountvoucherline',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='accountvoucher',
            index=models.Index(fields=['account_no', '-voucher_date'], name='fin_account_account_9304fb_idx'),
        ),
        migrations.AddIndex(
            model_name='accountvoucher',
            index=models.Index(fields=['voucher_type', '-voucher_date'], name='fin_account_voucher_88a5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='accountvoucher',
            index=models.Index(fields=['posted', '-voucher_date'], name='fin_account_posted_cbea7f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountvoucher',
            index=models.Index(fields=['status'], name='fin_account_status_817f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='accountvoucherline',
            index=models.Index(fields=['account_no', '-voucher_date'], name='fin_account_account_b4f648_idx'),
        ),
        migrations.AddIndex(
            model_name='accountvoucherline',
            index=models.Index(fields=['voucher_no'], name='fin_account_voucher_ec7e3b_idx'),
        ),
    ]
