# Generated by Django 5.2.15 on 2026-06-17 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(default='Industrial ERP', max_length=160)),
                ('company_logo', models.ImageField(blank=True, upload_to='branding/logos/')),
                ('company_tagline', models.CharField(blank=True, default='Official MIS Portal', max_length=220)),
                ('md_name', models.CharField(blank=True, max_length=120, verbose_name='Managing Director name')),
                ('md_picture', models.ImageField(blank=True, upload_to='branding/md/')),
                ('md_message', models.TextField(blank=True, default='Please use this system responsibly for official work only.')),
                ('mis_helpline_phone', models.CharField(blank=True, max_length=40)),
                ('mis_helpline_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=40)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=20)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10)),
                ('login_background_image', models.ImageField(blank=True, upload_to='branding/login/')),
                ('footer_text', models.CharField(blank=True, default='Authorized users only.', max_length=220)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System setting',
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
