# Generated by Django 5.2.15 on 2026-09-07 07:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_systemsetting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='wheat_brokerage_rate_per_100kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='wheat_withholding_rate_per_40kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
