from django.urls import path

from .views import DirectPurchaseCreateView, CustomerCreateView, CustomerLedgerListView, GRNBulkReceiveView, GRNColumnsView, GRNDetailView, GRNExportView, GRNListView, GRNPrintView, LedgerPrintView, PurchaseReturnQuickCreateView, PurchaseReturnReceiptView, POSReturnQuickCreateView, POSReturnReceiptView, PurchaseOrderDraftFinalizeView, PurchaseOrderDraftInitView, PurchaseOrderColumnsView, PurchaseOrderExportView, PurchaseOrderFormSettingsView, PurchaseOrderRaiseView, PurchaseOrderCancelView, PurchaseOrderCloseShortView, PurchaseOrderReopenView, PurchaseApprovalLimitView, GoodsReceiptReverseView, GoodsReceiptCreateView, PurchaseBillCreateView, PurchaseBillDetailView, PurchaseBillListView, PurchaseBillReverseView, CustomerListView, CustomerUpdateView, CustomerToggleStatusView, CustomerToggleDefaultView, InventoryClassCreateView, InventoryClassListView, InventoryClassUpdateView, InventoryClassToggleStatusView, UOMToggleStatusView, ItemCreateView, ItemExportView, ItemImportSampleView, ItemImportView, ItemConversionOptionsView, ItemListView, ItemNextCodeView, ItemPrintView, ItemUpdateView, ItemToggleStatusView, LedgerListView, POSCheckoutView, POSCreateView, POSDetailView, POSListView, POSReceiptView, POSUpdateView, POSReturnCreateView, POSReturnDetailView, POSReturnItemCreateView, POSReturnListView, POSReturnPostView, PurchaseOrderCreateView, PurchaseOrderDetailView, ManualTransactionView, ManualTransactionAddView, ManualTransactionDeleteView, ManualTransactionToggleView, ManualTransactionSubmitView, ManualTransactionPrintView, PurchaseOrderItemCreateView, PurchaseOrderItemToggleStatusView, PurchaseOrderItemUpdateView, PurchaseOrderLinesUpdateView, PurchaseInvoiceDetailView, PurchaseInvoiceExportView, PurchaseInvoiceListView, SupplierGRNOptionsView, SaleInvoiceCreateView, SaleInvoiceListView, PurchaseOrderListView, PurchaseOrderPrintView, PurchaseOrderQuickCreateView, PurchaseOrderUpdateView, PurchaseReceiveView, PurchaseReportView, PurchaseReturnCreateView, PurchaseReturnDetailView, PurchaseReturnItemCreateView, PurchaseReturnListView, PurchaseReturnPostView, UOMConversionCreateView, UOMConversionListView, UOMConversionUpdateView, UOMConversionToggleStatusView, UOMCreateView, UOMListView, UOMUpdateView, SupplierCreateView, SupplierDetailView, SupplierListView, SupplierUpdateView, SupplierToggleStatusView

app_name = "inventory"

urlpatterns = [
    path("classes/", InventoryClassListView.as_view(), name="class_list"),
    path("classes/new/", InventoryClassCreateView.as_view(), name="class_create"),
    path("classes/<int:pk>/edit/", InventoryClassUpdateView.as_view(), name="class_update"),
    path("classes/<int:pk>/toggle-status/", InventoryClassToggleStatusView.as_view(), name="class_toggle_status"),
    path("uoms/", UOMListView.as_view(), name="uom_list"),
    path("uoms/new/", UOMCreateView.as_view(), name="uom_create"),
    path("uoms/<int:pk>/edit/", UOMUpdateView.as_view(), name="uom_update"),
    path("uoms/<int:pk>/toggle-status/", UOMToggleStatusView.as_view(), name="uom_toggle_status"),
    path("uom-conversions/", UOMConversionListView.as_view(), name="conversion_list"),
    path("uom-conversions/new/", UOMConversionCreateView.as_view(), name="conversion_create"),
    path("uom-conversions/<int:pk>/edit/", UOMConversionUpdateView.as_view(), name="conversion_update"),
    path("uom-conversions/<int:pk>/toggle-status/", UOMConversionToggleStatusView.as_view(), name="conversion_toggle_status"),
    path("suppliers/", SupplierListView.as_view(), name="supplier_list"),
    path("suppliers/<int:pk>/", SupplierDetailView.as_view(), name="supplier_detail"),
    path("suppliers/new/", SupplierCreateView.as_view(), name="supplier_create"),
    path("suppliers/<int:pk>/edit/", SupplierUpdateView.as_view(), name="supplier_update"),
    path("suppliers/<int:pk>/toggle-status/", SupplierToggleStatusView.as_view(), name="supplier_toggle_status"),
    path("items/", ItemListView.as_view(), name="item_list"),
    path("items/print/", ItemPrintView.as_view(), name="item_print"),
    path("items/export/", ItemExportView.as_view(), name="item_export"),
    path("items/import/", ItemImportView.as_view(), name="item_import"),
    path("items/import/sample/", ItemImportSampleView.as_view(), name="item_import_sample"),
    path("items/new/", ItemCreateView.as_view(), name="item_create"),
    path("items/next-code/", ItemNextCodeView.as_view(), name="item_next_code"),
    path("items/conversion-options/", ItemConversionOptionsView.as_view(), name="item_conversion_options"),
    path("items/<int:pk>/edit/", ItemUpdateView.as_view(), name="item_update"),
    path("items/<int:pk>/toggle-status/", ItemToggleStatusView.as_view(), name="item_toggle_status"),
    path("ledger/", LedgerListView.as_view(), name="ledger_list"),
    path("ledger/print/", LedgerPrintView.as_view(), name="ledger_print"),
    path("customer-ledger/", CustomerLedgerListView.as_view(), name="customer_ledger_list"),
    path("grn/", GRNListView.as_view(), name="grn_list"),
    path("grn/new/", GoodsReceiptCreateView.as_view(), name="goods_receipt_create"),
    path("grn/columns/", GRNColumnsView.as_view(), name="grn_columns"),
    path("grn/export/", GRNExportView.as_view(), name="grn_export"),
    # Keyed on the note number rather than a row id: a note covering four
    # lines is one document, and its number is what anybody holding the
    # paper can read off it.
    path("grn/note/<str:number>/", GRNDetailView.as_view(), name="grn_detail"),
    path("grn/<int:pk>/receive/", GRNBulkReceiveView.as_view(), name="grn_bulk_receive"),
    path("grn/<int:pk>/print/", GRNPrintView.as_view(), name="grn_print"),
    path("purchase-orders/", PurchaseOrderListView.as_view(), name="purchase_order_list"),
    path("purchase-orders/new/", PurchaseOrderCreateView.as_view(), name="purchase_order_create"),
    path("purchase-orders/export/", PurchaseOrderExportView.as_view(), name="purchase_order_export"),
    path("purchase-orders/columns/", PurchaseOrderColumnsView.as_view(), name="purchase_order_columns"),
    path("purchase-orders/form-settings/", PurchaseOrderFormSettingsView.as_view(), name="purchase_order_form_settings"),
    path("purchases/", PurchaseInvoiceListView.as_view(), name="purchase_invoice_list"),
    path("purchases/export/", PurchaseInvoiceExportView.as_view(), name="purchase_invoice_export"),
    # Its own page rather than the order detail: the two documents are read
    # for different reasons, and only one of them is still owed anything.
    path("purchases/<int:pk>/", PurchaseInvoiceDetailView.as_view(), name="purchase_invoice_detail"),
    path("sales/", SaleInvoiceListView.as_view(), name="sale_invoice_list"),
    path("sales/new/", SaleInvoiceCreateView.as_view(), name="sale_invoice_create"),
    path("purchases/new/", DirectPurchaseCreateView.as_view(), name="direct_purchase_create"),
    # What the direct purchase screen asks for the moment a supplier is
    # picked: that supplier's goods receipts, to copy lines from.
    path("purchases/grn-options/", SupplierGRNOptionsView.as_view(), name="supplier_grn_options"),
    path("purchase-orders/quick-create/", PurchaseOrderQuickCreateView.as_view(), name="purchase_order_quick_create"),
    path("purchase-orders/draft-init/", PurchaseOrderDraftInitView.as_view(), name="purchase_order_draft_init"),
    path("purchase-orders/draft-finalize/", PurchaseOrderDraftFinalizeView.as_view(), name="purchase_order_draft_finalize"),
    path("purchase-orders/<int:pk>/raise/", PurchaseOrderRaiseView.as_view(), name="purchase_order_raise"),
    # Ending an order early. Two verbs, not one: cancel is for an order nothing
    # arrived against, close-short for one that was part delivered.
    path("purchase-orders/<int:pk>/cancel/", PurchaseOrderCancelView.as_view(), name="purchase_order_cancel"),
    path("purchase-orders/<int:pk>/close-short/", PurchaseOrderCloseShortView.as_view(), name="purchase_order_close_short"),
    path("purchase-orders/<int:pk>/reopen/", PurchaseOrderReopenView.as_view(), name="purchase_order_reopen"),
    path("purchase-orders/approval-limit/", PurchaseApprovalLimitView.as_view(), name="purchase_approval_limit"),
    # Supplier bills, matched against the goods that actually arrived.
    path("purchase-bills/", PurchaseBillListView.as_view(), name="purchase_bill_list"),
    path("purchase-bills/new/", PurchaseBillCreateView.as_view(), name="purchase_bill_create"),
    path("purchase-bills/<int:pk>/", PurchaseBillDetailView.as_view(), name="purchase_bill_detail"),
    path("purchase-bills/<int:pk>/reverse/", PurchaseBillReverseView.as_view(), name="purchase_bill_reverse"),
    path("goods-receipts/<int:pk>/reverse/", GoodsReceiptReverseView.as_view(), name="goods_receipt_reverse"),
    path("purchase-orders/<int:pk>/edit/", PurchaseOrderUpdateView.as_view(), name="purchase_order_update"),
    path("purchase-orders/<int:pk>/", PurchaseOrderDetailView.as_view(), name="purchase_order_detail"),
    path("purchase-orders/<int:pk>/items/new/", PurchaseOrderItemCreateView.as_view(), name="purchase_order_item_create"),
    path("purchase-order-items/<int:pk>/edit/", PurchaseOrderItemUpdateView.as_view(), name="purchase_order_item_update"),
    path("purchase-order-items/<int:pk>/toggle-status/", PurchaseOrderItemToggleStatusView.as_view(), name="purchase_order_item_toggle_status"),
    path("purchase-orders/<int:pk>/lines/", PurchaseOrderLinesUpdateView.as_view(), name="purchase_order_lines_update"),
    path("purchase-orders/<int:pk>/print/", PurchaseOrderPrintView.as_view(), name="purchase_order_print"),
    path("manual-transactions/", ManualTransactionView.as_view(), name="manual_transaction"),
    path("manual-transactions/add/", ManualTransactionAddView.as_view(), name="manual_transaction_add"),
    path("manual-transactions/<int:pk>/toggle/", ManualTransactionToggleView.as_view(), name="manual_transaction_toggle"),
    path("manual-transactions/<int:pk>/delete/", ManualTransactionDeleteView.as_view(), name="manual_transaction_delete"),
    path("manual-transactions/submit/", ManualTransactionSubmitView.as_view(), name="manual_transaction_submit"),
    path("manual-transactions/<str:tx_id>/print/", ManualTransactionPrintView.as_view(), name="manual_transaction_print"),
    path("purchase-orders/<int:pk>/receive/", PurchaseReceiveView.as_view(), name="purchase_order_receive"),
    path("customers/", CustomerListView.as_view(), name="customer_list"),
    path("customers/new/", CustomerCreateView.as_view(), name="customer_create"),
    path("customers/<int:pk>/edit/", CustomerUpdateView.as_view(), name="customer_update"),
    path("customers/<int:pk>/toggle-status/", CustomerToggleStatusView.as_view(), name="customer_toggle_status"),
    path("customers/<int:pk>/toggle-default/", CustomerToggleDefaultView.as_view(), name="customer_toggle_default"),
    path("pos-sales/", POSListView.as_view(), name="pos_list"),
    path("pos-sales/new/", POSCreateView.as_view(), name="pos_create"),
    path("pos-sales/<int:pk>/", POSDetailView.as_view(), name="pos_detail"),
    path("pos-sales/<int:pk>/edit/", POSUpdateView.as_view(), name="pos_update"),
    path("pos-sales/checkout/", POSCheckoutView.as_view(), name="pos_checkout"),
    path("pos-sales/<int:pk>/receipt/", POSReceiptView.as_view(), name="pos_receipt"),
    path("pos-returns/", POSReturnListView.as_view(), name="pos_return_list"),
    path("pos-returns/quick-create/", POSReturnQuickCreateView.as_view(), name="pos_return_quick_create"),
    path("pos-returns/new/", POSReturnCreateView.as_view(), name="pos_return_create"),
    path("pos-returns/<int:pk>/", POSReturnDetailView.as_view(), name="pos_return_detail"),
    path("pos-returns/<int:pk>/items/new/", POSReturnItemCreateView.as_view(), name="pos_return_item_create"),
    path("pos-returns/<int:pk>/post/", POSReturnPostView.as_view(), name="pos_return_post"),
    path("pos-returns/<int:pk>/receipt/", POSReturnReceiptView.as_view(), name="pos_return_receipt"),
    path("purchase-returns/", PurchaseReturnListView.as_view(), name="purchase_return_list"),
    path("purchase-returns/quick-create/", PurchaseReturnQuickCreateView.as_view(), name="purchase_return_quick_create"),
    path("purchase-returns/<int:pk>/receipt/", PurchaseReturnReceiptView.as_view(), name="purchase_return_receipt"),
    path("purchase-returns/new/", PurchaseReturnCreateView.as_view(), name="purchase_return_create"),
    path("purchase-returns/<int:pk>/", PurchaseReturnDetailView.as_view(), name="purchase_return_detail"),
    path("purchase-returns/<int:pk>/items/new/", PurchaseReturnItemCreateView.as_view(), name="purchase_return_item_create"),
    path("purchase-returns/<int:pk>/post/", PurchaseReturnPostView.as_view(), name="purchase_return_post"),
    path("reports/ledger/", LedgerListView.as_view(), name="report_ledger"),
    path("reports/purchases/", PurchaseReportView.as_view(), name="report_purchase"),
    path("reports/sales/", POSListView.as_view(), name="report_sale"),
    path("reports/sale-returns/", POSReturnListView.as_view(), name="report_sale_return"),
    path("reports/purchase-returns/", PurchaseReturnListView.as_view(), name="report_purchase_return"),
]
