from django.urls import path

from .views import CustomerCreateView, CustomerListView, CustomerUpdateView, CustomerToggleStatusView, CustomerToggleDefaultView, InventoryClassCreateView, InventoryClassListView, InventoryClassUpdateView, ItemCreateView, ItemListView, ItemUpdateView, LedgerListView, POSCreateView, POSDetailView, POSItemCreateView, POSListView, POSPostView, POSUpdateView, POSReturnCreateView, POSReturnDetailView, POSReturnItemCreateView, POSReturnListView, POSReturnPostView, PurchaseOrderCreateView, PurchaseOrderDetailView, ManualTransactionView, ManualTransactionAddView, ManualTransactionToggleView, ManualTransactionSubmitView, PurchaseOrderItemCreateView, PurchaseOrderItemToggleStatusView, PurchaseOrderItemUpdateView, PurchaseOrderListView, PurchaseOrderPrintView, PurchaseOrderUpdateView, PurchaseReceiveView, PurchaseReturnCreateView, PurchaseReturnDetailView, PurchaseReturnItemCreateView, PurchaseReturnListView, PurchaseReturnPostView, StockListView, UOMConversionCreateView, UOMConversionListView, UOMConversionUpdateView, UOMCreateView, UOMListView, UOMUpdateView, VendorCreateView, VendorListView, VendorUpdateView

app_name = "inventory"

urlpatterns = [
    path("classes/", InventoryClassListView.as_view(), name="class_list"),
    path("classes/new/", InventoryClassCreateView.as_view(), name="class_create"),
    path("classes/<int:pk>/edit/", InventoryClassUpdateView.as_view(), name="class_update"),
    path("uoms/", UOMListView.as_view(), name="uom_list"),
    path("uoms/new/", UOMCreateView.as_view(), name="uom_create"),
    path("uoms/<int:pk>/edit/", UOMUpdateView.as_view(), name="uom_update"),
    path("uom-conversions/", UOMConversionListView.as_view(), name="conversion_list"),
    path("uom-conversions/new/", UOMConversionCreateView.as_view(), name="conversion_create"),
    path("uom-conversions/<int:pk>/edit/", UOMConversionUpdateView.as_view(), name="conversion_update"),
    path("vendors/", VendorListView.as_view(), name="vendor_list"),
    path("vendors/new/", VendorCreateView.as_view(), name="vendor_create"),
    path("vendors/<int:pk>/edit/", VendorUpdateView.as_view(), name="vendor_update"),
    path("items/", ItemListView.as_view(), name="item_list"),
    path("items/new/", ItemCreateView.as_view(), name="item_create"),
    path("items/<int:pk>/edit/", ItemUpdateView.as_view(), name="item_update"),
    path("stocks/", StockListView.as_view(), name="stock_list"),
    path("ledger/", LedgerListView.as_view(), name="ledger_list"),
    path("purchase-orders/", PurchaseOrderListView.as_view(), name="purchase_order_list"),
    path("purchase-orders/new/", PurchaseOrderCreateView.as_view(), name="purchase_order_create"),
    path("purchase-orders/<int:pk>/edit/", PurchaseOrderUpdateView.as_view(), name="purchase_order_update"),
    path("purchase-orders/<int:pk>/", PurchaseOrderDetailView.as_view(), name="purchase_order_detail"),
    path("purchase-orders/<int:pk>/items/new/", PurchaseOrderItemCreateView.as_view(), name="purchase_order_item_create"),
    path("purchase-order-items/<int:pk>/edit/", PurchaseOrderItemUpdateView.as_view(), name="purchase_order_item_update"),
    path("purchase-order-items/<int:pk>/toggle-status/", PurchaseOrderItemToggleStatusView.as_view(), name="purchase_order_item_toggle_status"),
    path("purchase-orders/<int:pk>/print/", PurchaseOrderPrintView.as_view(), name="purchase_order_print"),
    path("manual-transactions/", ManualTransactionView.as_view(), name="manual_transaction"),
    path("manual-transactions/add/", ManualTransactionAddView.as_view(), name="manual_transaction_add"),
    path("manual-transactions/<int:pk>/toggle/", ManualTransactionToggleView.as_view(), name="manual_transaction_toggle"),
    path("manual-transactions/submit/", ManualTransactionSubmitView.as_view(), name="manual_transaction_submit"),
    path("purchase-orders/<int:pk>/receive/", PurchaseReceiveView.as_view(), name="purchase_order_receive"),
    path("customers/", CustomerListView.as_view(), name="customer_list"),
    path("customers/new/", CustomerCreateView.as_view(), name="customer_create"),
    path("customers/<int:pk>/edit/", CustomerUpdateView.as_view(), name="customer_update"),
    path("customers/<int:pk>/toggle-status/", CustomerToggleStatusView.as_view(), name="customer_toggle_status"),
    path("customers/<int:pk>/toggle-default/", CustomerToggleDefaultView.as_view(), name="customer_toggle_default"),
    path("pos-sales/", POSListView.as_view(), name="pos_list"),
    path("pos-sales/new/", POSCreateView.as_view(), name="pos_create"),
    path("pos-sales/<int:pk>/", POSDetailView.as_view(), name="pos_detail"),
    path("pos-sales/<int:pk>/edit/", POSUpdateView.as_view(), name="pos_update"),
    path("pos-sales/<int:pk>/items/new/", POSItemCreateView.as_view(), name="pos_item_create"),
    path("pos-sales/<int:pk>/post/", POSPostView.as_view(), name="pos_post"),
    path("pos-returns/", POSReturnListView.as_view(), name="pos_return_list"),
    path("pos-returns/new/", POSReturnCreateView.as_view(), name="pos_return_create"),
    path("pos-returns/<int:pk>/", POSReturnDetailView.as_view(), name="pos_return_detail"),
    path("pos-returns/<int:pk>/items/new/", POSReturnItemCreateView.as_view(), name="pos_return_item_create"),
    path("pos-returns/<int:pk>/post/", POSReturnPostView.as_view(), name="pos_return_post"),
    path("purchase-returns/", PurchaseReturnListView.as_view(), name="purchase_return_list"),
    path("purchase-returns/new/", PurchaseReturnCreateView.as_view(), name="purchase_return_create"),
    path("purchase-returns/<int:pk>/", PurchaseReturnDetailView.as_view(), name="purchase_return_detail"),
    path("purchase-returns/<int:pk>/items/new/", PurchaseReturnItemCreateView.as_view(), name="purchase_return_item_create"),
    path("purchase-returns/<int:pk>/post/", PurchaseReturnPostView.as_view(), name="purchase_return_post"),
    path("reports/stock/", StockListView.as_view(), name="report_stock"),
    path("reports/ledger/", LedgerListView.as_view(), name="report_ledger"),
    path("reports/purchases/", PurchaseOrderListView.as_view(), name="report_purchase"),
    path("reports/sales/", POSListView.as_view(), name="report_sale"),
    path("reports/sale-returns/", POSReturnListView.as_view(), name="report_sale_return"),
    path("reports/purchase-returns/", PurchaseReturnListView.as_view(), name="report_purchase_return"),
]
