from django.urls import path

from .views import (
    AccountConfigurationCreateView,
    AccountConfigurationDetailView,
    AccountConfigurationToggleStatusView,
    FiscalYearDetailView,
    AccountConfigurationListView,
    AccountConfigurationUpdateView,
    BalanceSheetView,
    CashFlowView,
    ChartOfAccountCreateView,
    ChartOfAccountDeleteView,
    ChartOfAccountRenameView,
    ChartOfAccountReorderView,
    ChartOfAccountTreeView,
    AccountVoucherCreateView,
    AccountVoucherDetailView,
    AccountVoucherLineCreateView,
    AccountVoucherLineDeleteView,
    AccountLedgerExportView,
    AccountLedgerView,
    AccountVoucherExportView,
    AccountVoucherListView,
    AccountVoucherUpdateView,
    DaybookView,
    IncomeStatementView,
    AccountBalanceView,
    AccountVoucherPrintView,
    NextVoucherNumberView,
    InventoryValuationView,
    PeriodCloseView,
    OpeningBalanceView,
    TrialBalanceView,
    FiscalPeriodSetActiveView,
    FiscalYearToggleActiveView,
    FiscalYearCreateView,
    FiscalYearListView,
    FiscalYearUpdateView,
)

app_name = "finance"

urlpatterns = [
    path("fiscal-years/", FiscalYearListView.as_view(), name="fiscal_year_list"),
    path("fiscal-years/new/", FiscalYearCreateView.as_view(), name="fiscal_year_create"),
    path("fiscal-years/<int:pk>/", FiscalYearDetailView.as_view(), name="fiscal_year_detail"),
    path("fiscal-years/<int:pk>/edit/", FiscalYearUpdateView.as_view(), name="fiscal_year_update"),
    path("fiscal-years/<int:pk>/set-active-period/", FiscalPeriodSetActiveView.as_view(), name="fiscal_period_set_active"),
    path("fiscal-years/<int:pk>/toggle-active/", FiscalYearToggleActiveView.as_view(), name="fiscal_year_toggle_active"),
    path("accounts/", AccountConfigurationListView.as_view(), name="account_configuration_list"),
    path("accounts/new/", AccountConfigurationCreateView.as_view(), name="account_configuration_create"),
    path("accounts/<int:pk>/", AccountConfigurationDetailView.as_view(), name="account_configuration_detail"),
    path("accounts/<int:pk>/edit/", AccountConfigurationUpdateView.as_view(), name="account_configuration_update"),
    path("accounts/<int:pk>/toggle-status/", AccountConfigurationToggleStatusView.as_view(), name="account_configuration_toggle_status"),
    path("chart-of-accounts/", ChartOfAccountTreeView.as_view(), name="chart_of_accounts"),
    path("chart-of-accounts/create/", ChartOfAccountCreateView.as_view(), name="coa_create"),
    path("chart-of-accounts/reorder/", ChartOfAccountReorderView.as_view(), name="coa_reorder"),
    path("chart-of-accounts/<int:pk>/rename/", ChartOfAccountRenameView.as_view(), name="coa_rename"),
    path("chart-of-accounts/<int:pk>/delete/", ChartOfAccountDeleteView.as_view(), name="coa_delete"),
    path("opening-balances/", OpeningBalanceView.as_view(), name="opening_balances"),
    path("trial-balance/", TrialBalanceView.as_view(), name="trial_balance"),
    path("income-statement/", IncomeStatementView.as_view(), name="income_statement"),
    path("balance-sheet/", BalanceSheetView.as_view(), name="balance_sheet"),
    path("cash-flow/", CashFlowView.as_view(), name="cash_flow"),
    path("period-close/", PeriodCloseView.as_view(), name="period_close"),
    path("inventory-valuation/", InventoryValuationView.as_view(), name="inventory_valuation"),
    path("ledger/", AccountLedgerView.as_view(), name="account_ledger"),
    path("ledger/export/", AccountLedgerExportView.as_view(), name="account_ledger_export"),
    path("daybook/", DaybookView.as_view(), name="daybook"),
    path("vouchers/", AccountVoucherListView.as_view(), name="account_voucher_list"),
    path("vouchers/export/", AccountVoucherExportView.as_view(), name="account_voucher_export"),
    path("vouchers/new/", AccountVoucherCreateView.as_view(), name="account_voucher_create"),
    path("vouchers/next-number/", NextVoucherNumberView.as_view(), name="next_voucher_number"),
    path("vouchers/account-balance/", AccountBalanceView.as_view(), name="account_balance"),
    path("vouchers/<int:pk>/", AccountVoucherDetailView.as_view(), name="account_voucher_detail"),
    path("vouchers/<int:pk>/print/", AccountVoucherPrintView.as_view(), name="account_voucher_print"),
    path("vouchers/<int:pk>/edit/", AccountVoucherUpdateView.as_view(), name="account_voucher_update"),
    path("vouchers/<int:voucher_pk>/lines/new/", AccountVoucherLineCreateView.as_view(), name="account_voucher_line_create"),
    path("vouchers/<int:voucher_pk>/lines/<int:pk>/delete/", AccountVoucherLineDeleteView.as_view(), name="account_voucher_line_delete"),
]

from .report_views import (  # noqa: E402
    AuditTrailColumnsView,
    AuditTrailExportView,
    AuditTrailView,
    BankBookColumnsView,
    BankBookExportView,
    BankBookView,
    CashBookColumnsView,
    CashBookExportView,
    CashBookView,
    ExpenseAnalysisColumnsView,
    ExpenseAnalysisExportView,
    ExpenseAnalysisView,
    OpeningBalancesColumnsView,
    OpeningBalancesExportView,
    OpeningBalancesView,
    PartyLedgerColumnsView,
    PartyLedgerExportView,
    PartyLedgerView,
    ReceivablePayableColumnsView,
    ReceivablePayableExportView,
    ReceivablePayableView,
    VoucherRegisterColumnsView,
    VoucherRegisterExportView,
    VoucherRegisterView,
)

_REPORTS = (
    ("cash-book", "report_cash_book", CashBookView, CashBookExportView, CashBookColumnsView),
    ("bank-book", "report_bank_book", BankBookView, BankBookExportView, BankBookColumnsView),
    ("party-ledger", "report_party_ledger", PartyLedgerView, PartyLedgerExportView, PartyLedgerColumnsView),
    ("voucher-register", "report_voucher_register", VoucherRegisterView, VoucherRegisterExportView, VoucherRegisterColumnsView),
    ("expense-analysis", "report_expense_analysis", ExpenseAnalysisView, ExpenseAnalysisExportView, ExpenseAnalysisColumnsView),
    ("receivable-payable", "report_receivable_payable", ReceivablePayableView, ReceivablePayableExportView, ReceivablePayableColumnsView),
    ("opening-balances", "report_opening_balances", OpeningBalancesView, OpeningBalancesExportView, OpeningBalancesColumnsView),
    ("audit-trail", "report_audit_trail", AuditTrailView, AuditTrailExportView, AuditTrailColumnsView),
)
for _slug, _name, _screen, _export, _columns in _REPORTS:
    urlpatterns += [
        path(f"reports/{_slug}/", _screen.as_view(), name=_name),
        path(f"reports/{_slug}/export/", _export.as_view(), name=f"{_name}_export"),
        path(f"reports/{_slug}/columns/", _columns.as_view(), name=f"{_name}_columns"),
    ]
