# Generated by Django 5.2.15 on 2026-09-21 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_nav_favourites',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['user', 'position'], name='ix_portal_nav_fav_user_pos')],
                'constraints': [models.UniqueConstraint(fields=('user', 'href'), name='uq_portal_nav_favourite')],
            },
        ),
    ]
