# Generated by Django 5.2.15 on 2026-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryclass',
            name='class_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Class Code'),
        ),
        migrations.AlterField(
            model_name='inventoryclass',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('partial_received', 'Partial Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=20),
        ),
    ]
