# Generated by Django 5.2.15 on 2026-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_manualtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtransaction',
            name='selected',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
