# Generated by Django 5.2.15 on 2026-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_manualtransaction_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
