# Generated by Django 5.2.15 on 2026-06-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_customer_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('raised', 'Raised'), ('partial_received', 'Partial Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled')], default='raised', max_length=20),
        ),
    ]
