# Generated by Django 5.2.15 on 2026-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('raised', 'Raised'), ('partial_received', 'Partial Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled')], default='raised', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderitemreceived',
            name='grn_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
