# Generated by Django 5.2.15 on 2026-06-30 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_grn_number_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_no', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('CASH_PAYMENT', 'Cash Payment'), ('RETURN', 'Return')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='inv_customer_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_customer_ledgers',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['transaction_no'], name='inv_custome_transac_bd3c01_idx'), models.Index(fields=['customer'], name='inv_custome_inv_cus_412897_idx')],
            },
        ),
    ]
