# Generated by Django 5.2.15 on 2026-06-30 15:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_customerledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerledger',
            options={'ordering': ['-transaction_date', '-id']},
        ),
        migrations.AddField(
            model_name='customerledger',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['transaction_date'], name='inv_custome_transac_a6c34d_idx'),
        ),
    ]
