# Generated by Django 5.2.15 on 2026-07-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_customerledger_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtransaction',
            name='vendor',
            field=models.ForeignKey(db_column='inv_config_vendor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor'),
        ),
    ]
