# Generated by Django 5.2.15 on 2026-07-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_manualtransaction_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
