# Generated by Django 5.2.15 on 2026-08-09 09:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_purchaseorderitem_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
