# Generated by Django 5.2.15 on 2026-08-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_vendor_credit_limit_vendor_credit_period_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
