# Generated by Django 5.2.15 on 2026-08-11 17:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_supplier_seed_code_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_kind',
            field=models.CharField(choices=[('P', 'Product'), ('S', 'Service')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Sale Price'),
        ),
    ]
