# Generated by Django 5.2.15 on 2026-08-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventoryitem_item_kind_inventoryitem_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_class',
            field=models.ForeignKey(blank=True, db_column='inv_config_class_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryclass'),
        ),
    ]
