# Generated by Django 5.2.15 on 2026-08-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_inventoryitem_item_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='secondary_uom',
            field=models.ForeignKey(blank=True, db_column='inv_config_secondary_uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_items', to='inventory.uom'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uom',
            field=models.ForeignKey(db_column='inv_config_uom_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.uom'),
        ),
    ]
