# Generated by Django 5.2.15 on 2026-08-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inventoryitem_secondary_uom_alter_inventoryitem_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='inv_config_uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.uom'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='inv_config_uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.uom'),
        ),
    ]
