# Generated by Django 5.2.15 on 2026-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_inventoryitem_uom_alter_purchaseorderitem_uom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryclass',
            options={'ordering': ['title'], 'verbose_name': 'item category', 'verbose_name_plural': 'item categories'},
        ),
        migrations.AlterField(
            model_name='inventoryclass',
            name='class_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Category Code'),
        ),
        migrations.AlterField(
            model_name='inventoryclass',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Category Name'),
        ),
    ]
