# Generated by Django 5.2.15 on 2026-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_purchaseorder_is_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
