# Generated by Django 5.2.15 on 2026-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_purchaseorder_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
