# Generated by Django 5.2.15 on 2026-08-21 13:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_purchaseorder_expected_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('seq_num', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('bill_num', models.CharField(blank=True, max_length=40, unique=True)),
                ('supplier_invoice_num', models.CharField(max_length=80)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('goods_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cleared_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('variance_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], default='posted', max_length=20)),
                ('reverse_reason', models.CharField(blank=True, max_length=40)),
                ('reversed_on', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inv_purchase_bills',
                'ordering': ['-bill_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('seq_num', models.PositiveIntegerField()),
                ('descr', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('receipt_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_perc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
            ],
            options={
                'db_table': 'inv_purchase_bill_items',
                'ordering': ['bill', 'seq_num'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='close_reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_column='closed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='short_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='short_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='billed_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='landed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='reversal_of',
            field=models.ForeignKey(blank=True, db_column='reversal_of_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.purchaseorderitemreceived'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='reverse_reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='reversed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='seq_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('raised', 'Raised'), ('partial_received', 'Partial Received'), ('fully_received', 'Fully Received'), ('closed_short', 'Closed Short'), ('cancelled', 'Cancelled')], default='raised', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('is_direct', 'seq_num'), name='uniq_purchase_seq_per_kind'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_order',
            field=models.ForeignKey(db_column='inv_purchase_order_id', on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='reversal_of',
            field=models.ForeignKey(blank=True, db_column='reversal_of_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.purchasebill'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(db_column='inv_config_supplier_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='bill',
            field=models.ForeignKey(db_column='inv_purchase_bill_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasebill'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='inventory_item',
            field=models.ForeignKey(db_column='inv_inventory_code_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='receipt',
            field=models.ForeignKey(db_column='inv_purchase_order_item_received_id', on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='inventory.purchaseorderitemreceived'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['bill_num'], name='inv_purchas_bill_nu_91cb33_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['bill_date'], name='inv_purchas_bill_da_354a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted')), fields=('supplier', 'supplier_invoice_num'), name='uniq_supplier_invoice_num'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasebillitem',
            unique_together={('bill', 'seq_num')},
        ),
    ]
