# Generated by Django 5.2.15 on 2026-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_backfill_receipt_landed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemledger',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING', 'Opening'), ('RECEIVE', 'Receive'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale Return'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], max_length=20),
        ),
    ]
