# Generated by Django 5.2.15 on 2026-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_itemledger_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('raised', 'Raised'), ('partial_received', 'Partial Received'), ('fully_received', 'Fully Received'), ('closed_short', 'Closed'), ('cancelled', 'Cancelled')], default='raised', max_length=20),
        ),
    ]
