# Generated by Django 5.2.15 on 2026-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='close_remarks',
            field=models.TextField(blank=True),
        ),
    ]
