# Generated by Django 5.2.15 on 2026-08-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_purchaseorder_close_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
