# Generated by Django 5.2.15 on 2026-08-30 05:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_purchaseorderitemreceived_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='dc_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='inspected_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
