# Generated by Django 5.2.15 on 2026-08-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_purchaseorderitemreceived_dc_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitemreceived',
            name='freight_amount',
        ),
    ]
