# Generated by Django 5.2.15 on 2026-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_purchaseorderitemreceived_freight_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitemreceived',
            name='driver_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
