# Generated by Django 5.2.15 on 2026-08-30 08:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_purchaseorderitemreceived_driver_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebillitem',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, db_column='inv_purchase_order_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='inventory.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='billed_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasebillitem',
            name='receipt',
            field=models.ForeignKey(blank=True, db_column='inv_purchase_order_item_received_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='inventory.purchaseorderitemreceived'),
        ),
    ]
