# Generated by Django 5.2.15 on 2026-09-01 15:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_remove_customerledger_inv_custome_inv_cus_412897_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_invoiced', 'Partially Invoiced'), ('fully_invoiced', 'Fully Invoiced'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='raised', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seq_num', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('invoice_num', models.CharField(blank=True, max_length=40, unique=True)),
                ('supplier_invoice_num', models.CharField(max_length=80)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('goods_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='posted', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('journal_ref', models.CharField(blank=True, max_length=80)),
                ('legacy_bill_no', models.CharField(blank=True, max_length=40)),
                ('reverse_reason', models.CharField(blank=True, max_length=40)),
                ('reversed_on', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_column='posted_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_purchase_invoices', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, db_column='inv_purchase_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.purchaseorder')),
                ('reversal_of', models.ForeignKey(blank=True, db_column='reversal_of_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.purchaseinvoice')),
                ('supplier', models.ForeignKey(db_column='inv_config_supplier_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_purchase_invoices',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seq_num', models.PositiveIntegerField()),
                ('descr', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_perc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(db_column='inv_inventory_code_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('invoice', models.ForeignKey(db_column='inv_purchase_invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseinvoice')),
                ('purchase_order_item', models.ForeignKey(blank=True, db_column='inv_purchase_order_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.purchaseorderitem')),
                ('uom', models.ForeignKey(blank=True, db_column='inv_config_uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.uom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_purchase_invoice_items',
                'ordering': ['invoice', 'seq_num'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_num'], name='inv_purchas_invoice_cb1178_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_date'], name='inv_purchas_invoice_ff26de_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status', '-invoice_date'], name='inv_purchas_status_d4102a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', '-invoice_date'], name='inv_purchas_inv_con_df798d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['purchase_order'], name='inv_purchas_inv_pur_576616_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted')), fields=('supplier', 'supplier_invoice_num'), name='uniq_supplier_invoice_number'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceline',
            index=models.Index(fields=['inventory_item', '-id'], name='inv_purchas_inv_inv_b5a9c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoiceline',
            unique_together={('invoice', 'seq_num')},
        ),
    ]
