# Generated by Django 5.2.15 on 2026-09-01 16:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_purchase_order_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posmaster',
            name='journal_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='posmaster',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posmaster',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_column='posted_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_sales_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seq_num', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('order_num', models.CharField(blank=True, max_length=40, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('customer_ref', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_invoiced', 'Partially Invoiced'), ('fully_invoiced', 'Fully Invoiced'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('close_reason', models.CharField(blank=True, max_length=40)),
                ('close_remarks', models.TextField(blank=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, db_column='closed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='inv_customer_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_sales_orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='posmaster',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='inv_sales_order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seq_num', models.PositiveIntegerField()),
                ('descr', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_perc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('qty_invoiced', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('closed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(db_column='inv_inventory_code_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('sales_order', models.ForeignKey(db_column='inv_sales_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.salesorder')),
                ('uom', models.ForeignKey(blank=True, db_column='inv_config_uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.uom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_sales_order_items',
                'ordering': ['sales_order', 'seq_num'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_num'], name='inv_sales_o_order_n_e3dcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_date'], name='inv_sales_o_order_d_e80f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', '-order_date'], name='inv_sales_o_status_5fa288_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', '-order_date'], name='inv_sales_o_inv_cus_e16ad0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorderitem',
            unique_together={('sales_order', 'seq_num')},
        ),
    ]
