# Generated by Django 5.2.15 on 2026-09-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_sales_order_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='reversal_of',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='updated_by',
        ),
        # The unique_together goes first: it is defined over ``bill``, so
        # dropping the field while the constraint still names it fails.
        migrations.AlterUniqueTogether(
            name='purchasebillitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='purchase_order_item',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemreceived',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemreceived',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemreceived',
            name='purchase_order_item',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemreceived',
            name='reversal_of',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemreceived',
            name='updated_by',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='uniq_purchase_seq_per_kind',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='inv_purchas_is_dire_d28540_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_direct',
        ),
        migrations.DeleteModel(
            name='PurchaseBill',
        ),
        migrations.DeleteModel(
            name='PurchaseBillItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItemReceived',
        ),
    ]
