# Generated by Django 5.2.15 on 2026-09-01 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_drop_bill_and_receipt_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseinvoice',
            name='uniq_supplier_invoice_number',
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_num',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted'), models.Q(('supplier_invoice_num', ''), _negated=True)), fields=('supplier', 'supplier_invoice_num'), name='uniq_supplier_invoice_number'),
        ),
    ]
