# Generated by Django 5.2.15 on 2026-09-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_optional_supplier_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
