# Generated by Django 5.2.15 on 2026-09-07 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_purchase_return_on_invoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='legacypurchasemaster',
            new_name='legacy_inv__transac_be2084_idx',
            old_name='inv_purchas_transac_639493_idx',
        ),
    ]
