"""Bardana on the purchase invoice: whose sacks, and what one weighs.

Ownership is what decides whether a sack is bought. All three kinds move the
product ledger, because the mill has custody of all three and grinding has to
see them; only the mill's own carry a price and reach the supplier's payable.
Blank on every line that is not sacks.
"""

# Generated by Django 5.2.15 on 2026-09-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_purchase_invoice_wheat_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='bag_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='bardana_ownership',
            field=models.CharField(blank=True, choices=[('mill', "Mill's own"), ('party', "Party's"), ('returnable', 'Returnable')], max_length=20),
        ),
    ]
