"""Brokerage and withholding: the two charges quoted against weight.

Both read off the credit weight the invoice bought -- brokerage per 100 kg,
withholding per 40 kg -- and neither is owed to the supplier. Brokerage is a
cost of buying owed to the broker; withholding is money kept back from the
supplier and owed to the revenue, so the supplier is credited with that much
less. The rate is stored beside the amount so a printed invoice can be checked
against what was agreed rather than only showing the answer.

Defaults are zero, so every invoice already entered reads exactly as before.
"""

# Generated by Django 5.2.15 on 2026-09-07 03:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_purchase_invoice_bardana'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='brokerage_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='brokerage_rate_per_100kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='withholding_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='withholding_rate_per_40kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
