"""Purchase orders may commit to wheat and bardana, not only stores items.

The order line gains the same two-kinds shape the invoice line has, with the
same check constraint behind it. An order still moves nothing -- it is a
commitment either way -- but until now the mill could only order the stores
items it buys least of, and the wheat it lives on could not be ordered ahead at
all.

Every existing line names an inventory item, so nothing is backfilled.
"""

# Generated by Django 5.2.15 on 2026-09-07 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_purchase_invoice_weight_charges'),
        ('products', '0002_productledger_bardana_item_productledger_godown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, db_column='prod_node_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='products.productnode'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, db_column='inv_inventory_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['product', '-id'], name='inv_po_line_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inventory_item__isnull', False), ('product__isnull', True)), models.Q(('inventory_item__isnull', True), ('product__isnull', False)), _connector='OR'), name='inv_po_line_one_item_kind'),
        ),
    ]
