# Generated by Django 5.2.15 on 2026-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_purchase_order_product_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='mill_load_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='mill_tare_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='party_load_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='party_tare_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
