# Generated by Django 5.2.15 on 2026-09-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_purchaseinvoiceline_mill_load_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='freight_paid_by_mill',
            field=models.BooleanField(default=False),
        ),
    ]
