# Generated by Django 5.2.15 on 2026-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_purchaseinvoice_freight_paid_by_mill'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='brokerage_borne_by_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
