# Generated by Django 5.2.15 on 2026-09-15 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_purchaseinvoice_brokerage_borne_by_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchasereturnmaster',
            name='inv_purchas_return__85a194_idx',
        ),
        migrations.AddField(
            model_name='purchasereturndetail',
            name='invoice_line',
            field=models.ForeignKey(blank=True, db_column='inv_purchase_invoice_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='inventory.purchaseinvoiceline'),
        ),
        migrations.AddField(
            model_name='purchasereturndetail',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='inv_config_uom_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.uom'),
        ),
        migrations.AddField(
            model_name='purchasereturnmaster',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnmaster',
            name='reverse_reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='purchasereturnmaster',
            name='reversed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posdetail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('submitted', 'Submitted'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='posreturndetail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('submitted', 'Submitted'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='posreturnmaster',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('submitted', 'Submitted'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('submitted', 'Submitted'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='return_num',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('submitted', 'Submitted'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='purchasereturnmaster',
            index=models.Index(fields=['supplier', '-return_date'], name='inv_pr_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnmaster',
            index=models.Index(fields=['purchase_invoice', '-return_date'], name='inv_pr_invoice_date_idx'),
        ),
    ]
