# Generated by Django 5.2.15 on 2026-09-21 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_purchase_return_rebuild'),
        ('products', '0003_party_bardana_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posdetail',
            name='product',
            field=models.ForeignKey(blank=True, db_column='prod_node_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='products.productnode'),
        ),
        migrations.AddField(
            model_name='posreturndetail',
            name='product',
            field=models.ForeignKey(blank=True, db_column='prod_node_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_return_lines', to='products.productnode'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(blank=True, db_column='prod_node_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='products.productnode'),
        ),
        migrations.AlterField(
            model_name='posdetail',
            name='inventory_item',
            field=models.ForeignKey(blank=True, db_column='inv_inventory_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='posreturndetail',
            name='inventory_item',
            field=models.ForeignKey(blank=True, db_column='inv_inventory_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, db_column='inv_inventory_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddIndex(
            model_name='posdetail',
            index=models.Index(fields=['product', '-id'], name='inv_pos_line_product_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['product', '-id'], name='inv_so_line_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='posdetail',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inventory_item__isnull', False), ('product__isnull', True)), models.Q(('inventory_item__isnull', True), ('product__isnull', False)), _connector='OR'), name='inv_pos_line_one_item_kind'),
        ),
        migrations.AddConstraint(
            model_name='posreturndetail',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inventory_item__isnull', False), ('product__isnull', True)), models.Q(('inventory_item__isnull', True), ('product__isnull', False)), _connector='OR'), name='inv_pos_ret_line_one_item_kind'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inventory_item__isnull', False), ('product__isnull', True)), models.Q(('inventory_item__isnull', True), ('product__isnull', False)), _connector='OR'), name='inv_so_line_one_item_kind'),
        ),
    ]
