# Generated by Django 5.2.15 on 2026-09-21 10:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_alter_allowancededuction_created_at_and_more'),
        ('inventory', '0056_sale_lines_carry_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', 'customer_name'], name='inv_cust_status_name_idx'),
        ),
    ]
