# Generated by Django 5.2.15 on 2026-06-18 11:10

import django.db.models.deletion
from django.db import migrations, models


def migrate_employee_banks(apps, schema_editor):
    Employee = apps.get_model("hr", "Employee")
    Bank = apps.get_model("configurations", "Bank")
    for employee in Employee.objects.exclude(bank_name__isnull=True).exclude(bank_name=""):
        bank, _ = Bank.objects.get_or_create(title=employee.bank_name.strip(), defaults={"code": "", "status": "active"})
        employee.bank = bank
        employee.save(update_fields=["bank"])


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_bank'),
        ('hr', '0001_initial'),
        ('organizations', '0002_alter_branch_city_alter_branch_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bank',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(blank=True, db_column='conf_bank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.bank'),
        ),
        migrations.RunPython(migrate_employee_banks, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.ForeignKey(blank=True, db_column='conf_blood_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='org_branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, db_column='conf_department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, db_column='conf_designation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='conf_gender_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.ForeignKey(blank=True, db_column='conf_job_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.jobtype'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.ForeignKey(blank=True, db_column='conf_marital_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='org_organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.ForeignKey(blank=True, db_column='conf_religion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.religion'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salutation',
            field=models.ForeignKey(blank=True, db_column='conf_salutation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.salutation'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='employee',
            field=models.ForeignKey(db_column='hr_employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='employee',
            field=models.ForeignKey(db_column='hr_employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='qualification',
            field=models.ForeignKey(db_column='conf_qualification_id', on_delete=django.db.models.deletion.PROTECT, related_name='employee_links', to='configurations.qualification'),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='specialization',
            field=models.ForeignKey(blank=True, db_column='conf_specialization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_qualifications', to='configurations.specialization'),
        ),
    ]
