# Generated by Django 5.2.15 on 2026-06-18 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        ('organizations', '0002_alter_branch_city_alter_branch_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(db_column='iams_permission_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='access_control.permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(db_column='iams_role_id', on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='access_control.role'),
        ),
        migrations.AlterField(
            model_name='userassignment',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='org_branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='userassignment',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='org_organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='userassignment',
            name='role',
            field=models.ForeignKey(db_column='iams_role_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='access_control.role'),
        ),
        migrations.AlterField(
            model_name='userassignment',
            name='user',
            field=models.ForeignKey(db_column='iams_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
