from decimal import Decimal

from apps.core.constants import STATUS_ACTIVE
from apps.inventory.models import InventoryClass, InventoryItem, UOM


# (item_name, class_code, uom_code, price)
ITEMS = [
    # ── Electronics ──────────────────────────────────────────────
    ("Samsung 65\" 4K Smart LED TV", "IT-HW", "EA", 185000),
    ("LG 55\" OLED TV", "IT-HW", "EA", 220000),
    ("Haier 1.5 Ton Inverter AC", "FA-MCH", "EA", 95000),
    ("Dawlance 1 Ton Split AC", "FA-MCH", "EA", 72000),
    ("Orient 1.5 Ton DC Inverter AC", "FA-MCH", "EA", 88000),
    ("Samsung Galaxy A55 Mobile", "IT-HW", "EA", 82000),
    ("iPhone 15 128GB", "IT-HW", "EA", 280000),
    ("Xiaomi Redmi Note 13", "IT-HW", "EA", 55000),
    ("Dell Laptop Core i7 16GB", "IT-HW", "EA", 185000),
    ("HP Laptop Core i5 8GB", "IT-HW", "EA", 120000),
    ("Lenovo ThinkPad X1 Carbon", "IT-HW", "EA", 260000),
    ("HP LaserJet Pro Printer", "IT-HW", "EA", 35000),
    ("Canon PIXMA Inkjet Printer", "IT-HW", "EA", 18000),
    ("TP-Link WiFi Router AC1200", "IT-NET", "EA", 6500),
    ("D-Link 8-Port Switch", "IT-NET", "EA", 5200),
    ("Samsung 1TB External HDD", "IT-HW", "EA", 14000),
    ("Seagate 2TB HDD Internal", "IT-HW", "EA", 12000),
    ("Kingston 16GB DDR4 RAM", "IT-HW", "EA", 4800),
    ("HP Wireless Mouse & Keyboard", "IT-HW", "SET", 3500),
    ("LG 24\" FHD Monitor", "IT-HW", "EA", 28000),
    ("UPS 1200VA Inverter", "IT-HW", "EA", 22000),
    ("Hisense 14 Cu.Ft Refrigerator", "FA-MCH", "EA", 68000),
    ("Dawlance 9 Cu.Ft Refrigerator", "FA-MCH", "EA", 52000),
    ("Haier Washing Machine 8Kg", "FA-MCH", "EA", 48000),
    ("PEL Microwave Oven 25L", "FA-MCH", "EA", 18000),
    # ── Kiryana / Grocery Store ───────────────────────────────────
    ("Basmati Rice Premium 5Kg", "FB-DRY", "PK", 1200),
    ("Super Kernel Rice 5Kg", "FB-DRY", "PK", 950),
    ("Sela Rice 25Kg", "FB-DRY", "BAG", 4200),
    ("Toor Dal 1Kg", "FB-DRY", "PK", 380),
    ("Moong Dal 1Kg", "FB-DRY", "PK", 350),
    ("Masoor Dal 1Kg", "FB-DRY", "PK", 290),
    ("Chana Dal 1Kg", "FB-DRY", "PK", 260),
    ("Rafhan Corn Oil 5L", "FB-DRY", "BTL", 2800),
    ("Sufi Cooking Oil 5L", "FB-DRY", "BTL", 2650),
    ("Eva Cooking Oil 2.5L", "FB-DRY", "BTL", 1400),
    ("Sunridge Canola Oil 3L", "FB-DRY", "BTL", 1750),
    ("Olper Milk 1L", "FB-FRS", "BTL", 175),
    ("Nestle Milkpak 1L", "FB-FRS", "BTL", 180),
    ("Engro Foods Omung 1L", "FB-FRS", "BTL", 165),
    ("Nurpur Butter 200g", "FB-FRS", "PK", 520),
    ("Haleeb Cream 200ml", "FB-FRS", "BTL", 180),
    ("National Iodized Salt 800g", "FB-DRY", "PK", 55),
    ("Shan Biryani Masala 60g", "FB-DRY", "PK", 65),
    ("Shan Karahi Masala 50g", "FB-DRY", "PK", 60),
    ("Mehran Chilli Powder 100g", "FB-DRY", "PK", 75),
    ("National Turmeric 100g", "FB-DRY", "PK", 55),
    ("Tapal Danedar Tea 950g", "FB-BEV", "PK", 1450),
    ("Lipton Yellow Label Tea 475g", "FB-BEV", "PK", 950),
    ("Nescafe Classic 200g", "FB-BEV", "BTL", 1800),
    ("Milo Chocolate Drink 400g", "FB-BEV", "PK", 620),
    ("Nestle Nesquik 300g", "FB-BEV", "PK", 480),
    ("Pepsi 1.5L Bottle", "FB-BEV", "BTL", 130),
    ("Coca-Cola 1.5L Bottle", "FB-BEV", "BTL", 130),
    ("7UP 1.5L Bottle", "FB-BEV", "BTL", 125),
    ("Sprite 1.5L Bottle", "FB-BEV", "BTL", 125),
    ("Sting Energy Drink 330ml", "FB-BEV", "BTL", 95),
    ("Sunsilk Shampoo 400ml", "CS-CLN", "BTL", 580),
    ("Head & Shoulders 360ml", "CS-CLN", "BTL", 650),
    ("Lifebuoy Soap Bar 170g", "CS-CLN", "EA", 80),
    ("Dettol Soap 115g", "CS-CLN", "EA", 95),
    ("Surf Excel 3Kg", "CS-CLN", "PK", 1450),
    ("Ariel Detergent 3Kg", "CS-CLN", "PK", 1520),
    ("Harpic Toilet Cleaner 500ml", "CS-CLN", "BTL", 320),
    ("Dettol Antiseptic 500ml", "CS-CLN", "BTL", 480),
    ("Vaseline Petroleum Jelly 250ml", "CS-CLN", "BTL", 350),
    ("Pampers Baby Dry S3 56pcs", "CS-MED", "PK", 1800),
    ("Molfix Diapers M 56pcs", "CS-MED", "PK", 1650),
    ("Colgate Total Toothpaste 150g", "CS-CLN", "EA", 185),
    ("Crest Toothpaste 130g", "CS-CLN", "EA", 210),
    ("Gillette Fusion Razor", "CS-CLN", "EA", 450),
    ("Always Ultra Thin Pads 8pcs", "CS-MED", "PK", 150),
    # ── Wheat / Flour / Grain Market ──────────────────────────────
    ("FAUJI Wheat Flour 10Kg", "FB-DRY", "BAG", 1100),
    ("Sunridge Wheat Flour 10Kg", "FB-DRY", "BAG", 1050),
    ("Bake Parlor Maida 1Kg", "FB-DRY", "PK", 115),
    ("National Semolina (Suji) 1Kg", "FB-DRY", "PK", 130),
    ("Wheat (Gandum) 40Kg", "RM-AGR", "BAG", 4800),
    ("Fine Wheat 40Kg", "RM-AGR", "BAG", 5200),
    ("Maize (Makka) 50Kg", "RM-AGR", "BAG", 4500),
    ("Barley (Jau) 50Kg", "RM-AGR", "BAG", 3800),
    ("Millet (Bajra) 50Kg", "RM-AGR", "BAG", 3500),
    ("Sorghum (Jowar) 50Kg", "RM-AGR", "BAG", 3200),
    ("Chickpeas (Kabuli Chana) 1Kg", "FB-DRY", "KG", 420),
    ("Green Gram (Moong) 1Kg", "FB-DRY", "KG", 370),
    ("Black-Eyed Peas 1Kg", "FB-DRY", "KG", 280),
    ("Red Lentil (Masoor) 1Kg", "FB-DRY", "KG", 290),
    ("Sesame Seeds (Til) 1Kg", "RM-AGR", "KG", 650),
    ("Mustard Seeds 1Kg", "RM-AGR", "KG", 380),
    ("Coriander Seeds 1Kg", "RM-AGR", "KG", 320),
    ("Cumin Seeds (Zeera) 1Kg", "RM-AGR", "KG", 1100),
    ("Fennel Seeds (Saunf) 1Kg", "RM-AGR", "KG", 480),
    ("Fenugreek Seeds (Methi) 1Kg", "RM-AGR", "KG", 220),
    ("Black Pepper (Kali Mirch) 100g", "RM-AGR", "PK", 220),
    ("Cloves (Laung) 100g", "RM-AGR", "PK", 350),
    ("Cardamom (Elaichi) 50g", "RM-AGR", "PK", 480),
    ("Cinnamon Sticks 100g", "RM-AGR", "PK", 180),
    ("Dried Dates (Khajoor) 1Kg", "FB-DRY", "PK", 550),
    ("Dried Apricots 500g", "FB-DRY", "PK", 680),
    ("Walnut (Akhrot) 500g", "FB-DRY", "PK", 950),
    ("Almonds (Badam) 500g", "FB-DRY", "PK", 1200),
    ("Peanuts (Mungphali) 1Kg", "FB-DRY", "KG", 480),
    ("Raisins (Kishmish) 500g", "FB-DRY", "PK", 520),
    ("Sugar (Cheeni) 1Kg", "FB-DRY", "KG", 180),
    ("Brown Sugar 1Kg", "FB-DRY", "KG", 220),
    ("Rock Salt (Lahori Namak) 1Kg", "FB-DRY", "KG", 45),
    ("Desi Ghee 1Kg", "FB-FRS", "KG", 1850),
    ("Vanaspati Ghee 1Kg", "FB-FRS", "PK", 550),
    # ── MRO / Industrial ─────────────────────────────────────────
    ("Castrol Engine Oil 4L 20W50", "CS-FUL", "BTL", 3200),
    ("Shell Rimula Engine Oil 5L", "CS-FUL", "BTL", 4800),
    ("Total Quartz Motor Oil 4L", "CS-FUL", "BTL", 3500),
    ("Diesel Fuel (HSD) per Litre", "CS-FUL", "L", 305),
    ("Petrol (Unleaded) per Litre", "CS-FUL", "L", 290),
    ("Safety Gloves (Leather)", "CS-PPE", "PR", 280),
    ("Safety Helmet (HDPE)", "CS-PPE", "EA", 350),
    ("Safety Shoes Steel Toe", "CS-PPE", "PR", 2800),
    ("Reflective Safety Vest", "CS-PPE", "EA", 450),
    ("Face Shield Polycarbonate", "CS-PPE", "EA", 620),
    ("Welding Electrode 3.2mm 5Kg", "MRO-MCH", "PK", 1200),
    ("Grinding Disc 4.5\" 25pcs", "MRO-MCH", "PK", 850),
    ("Cutting Disc 4\" 25pcs", "MRO-MCH", "PK", 780),
    ("Ball Bearing 6205", "MRO-SP", "EA", 480),
    ("V-Belt A-40", "MRO-MCH", "EA", 380),
    ("PVC Conduit 20mm 3m", "MRO-ELC", "EA", 120),
    ("Cable Wire 2.5mm 100m", "MRO-ELC", "ROLL", 5200),
    ("MCB 32A Single Pole", "MRO-ELC", "EA", 380),
    ("3-Pin Plug Socket", "MRO-ELC", "EA", 120),
    ("LED Bulb 12W E27", "MRO-ELC", "EA", 220),
    ("Tube Light LED 18W", "MRO-ELC", "EA", 380),
    ("PVC Pipe 1\" 6m", "CC-PLM", "EA", 480),
    ("GI Pipe 1.5\" 6m", "CC-STR", "EA", 1850),
    ("Cement OPC 50Kg", "CC-STR", "BAG", 1200),
    ("Steel Rebar 12mm 12m", "CC-STR", "EA", 3200),
    ("Sand (Reti) per Cubic Ft", "CC-STR", "M3", 2800),
    ("Crushed Stone Aggregate 3/4\"", "CC-STR", "M3", 3500),
    ("Red Brick per 1000 pcs", "CC-STR", "EA", 18000),
    ("Plywood Sheet 4x8 12mm", "CC-FIN", "EA", 2800),
    ("Gypsum Board 4x8", "CC-FIN", "EA", 1200),
    ("Ceramic Floor Tile 60x60", "CC-FIN", "EA", 280),
    # ── Office Supplies ───────────────────────────────────────────
    ("A4 Paper 80GSM Ream 500", "CS-OFF", "PK", 850),
    ("Ball Point Pen Box 50pcs", "CS-OFF", "BX", 380),
    ("Stapler Heavy Duty", "CS-OFF", "EA", 450),
    ("Scotch Tape 48mm x 66m", "CS-OFF", "ROLL", 280),
    ("File Folder A4 50pcs", "CS-OFF", "PK", 620),
    ("Whiteboard Marker Set 4pcs", "CS-OFF", "SET", 180),
    ("Calculator Casio FX-991EX", "CS-OFF", "EA", 3200),
    ("Spiral Notebook A4 200pg", "CS-OFF", "EA", 220),
]


def seed_items() -> int:
    uom_cache = {u.code: u for u in __import__('apps.inventory.models', fromlist=['UOM']).UOM.objects.all()}
    class_cache = {c.class_code: c for c in InventoryClass.objects.all()}
    created_count = 0
    for item_name, class_code, uom_code, price in ITEMS:
        uom = uom_cache.get(uom_code)
        item_class = class_cache.get(class_code)
        if not uom or not item_class:
            continue
        _, created = InventoryItem.objects.get_or_create(
            item_name=item_name,
            defaults={
                "uom": uom,
                "item_class": item_class,
                "price": Decimal(str(price)),
                "status": STATUS_ACTIVE,
                "imported": "L",
                "inventory": "I",
            },
        )
        created_count += int(created)
    return created_count
