# Generated by Django 5.2.15 on 2026-06-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_bank'),
        ('hr', '0002_alter_employee_bank_alter_employee_blood_group_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='allowance_deduction',
            field=models.ForeignKey(db_column='conf_allowance_deduction_id', on_delete=django.db.models.deletion.PROTECT, related_name='employee_salary_items', to='configurations.allowancededuction'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(db_column='hr_employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(db_column='hr_employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hr.employee'),
        ),
    ]
