# Generated by Django 5.2.15 on 2026-06-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_bank'),
        ('hr', '0002_alter_employee_bank_alter_employee_blood_group_and_more'),
        ('payroll', '0002_alter_employeesalary_allowance_deduction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('employee', 'allowance_deduction')},
        ),
    ]
