# Generated by Django 5.2.15 on 2026-06-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_bank'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, db_column='conf_city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='configurations.city'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(db_column='org_organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organization'),
        ),
    ]
