# Generated by Django 5.2.15 on 2026-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_address_organization_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cell',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='organization',
            name='fax',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
